# Generated by Django 5.2.17 on 2026-09-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=31, unique=True, verbose_name="nom d'espace"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                ("password_hash", models.CharField(blank=True, max_length=128)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de confirmation"),
                            ("provisioning", "Mise en service"),
                            ("ready", "Prêt"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="expiration de la réservation"),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("workflow_job_id", models.IntegerField(blank=True, null=True)),
                ("awx_status", models.CharField(blank=True, max_length=20)),
                ("awx_checked_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "réservation",
                "ordering": ["-created_at"],
            },
        ),
    ]
